### ISSUE TITLE
[Rule] No-missing-keys - Not working correctly

### ISSUE THREAD

**Issue by kendinikertenkelebek** [kazupon/eslint-plugin-vue-i18n#30]
I'm using the nested messages in a JSON file. And this error happening for every line like that:

`warning: 'materials.notice.text' does not exist (vue-i18n/no-missing-keys)`

But my page working perfectly. How can i fix this console warnings?

**Comment by kendinikertenkelebek** [comment]
And this morning errors are disappeared magically.

**Comment by lucafaggianelli** [comment]
I'm facing the same issue, moreover I get 2 identical warnings per each language file I have. Very weird, did you do something to solve the issue?
